### ISSUE TITLE
Consider using the anaconda python/r distribution and bioconda project to simplify installation

### ISSUE THREAD

**Issue by burkesquires** [csbbcompbio/CSBB-v3.0#1]
Hello,
You may want to consider using the Anaconda python/r distribution and bioconda (https://bioconda.github.io) project to simplify installation of the tools used here. Regards

**Comment by csbbcompbio** [comment]
Thanks a lot for your suggestion.
Auto install is still a work in progress and I will definitely try conda distributions to improve the overall experience.


Thanks,

Cheers !!
Praneet
